global using Basket.Api.Models;
global using BuildingBlocks.CQRS;
global using BuildingBlocks.Behaviors;
global using FluentValidation;
global using Basket.Api.Exceptions;
global using Carter;
global using Mapster;
global using MediatR;
global using Marten;